---
- name: Update apt repository cache on Debian/Ubuntu
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install common packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages[ansible_os_family | lower] }}"